### ISSUE TITLE
Cannot find Playername-Realm issue

### ISSUE THREAD

**Issue by futureproof123** [iraizo/AutoLayer#16]
As someone else mentioned on the curseforge comments, there is an issue where the addon is trying to invite people and it includes the realm name in the invite so it fails

Example, i am on Doomhowl realm so it wil sometimes show 
"Cannot find Playername-Doomhowl" 
![curseforgesnip](https://github.com/user-attachments/assets/fd117474-3956-467f-a7cd-4b7f4f8d52ab)

So I took a look at the files and made one change and so far I haven't seen any issues

In layering.lua

Line 230 -
`            InviteUnit(name)`
Line 233 -
`        InviteUnit(name) -- This specifically invites the player's name with realm, intended?`

Change it to:

Line 230 -
`            InviteUnit(name_without_realm)`

Line 233 -
`        InviteUnit(name_without_realm)`

**Comment by OriusKhan** [comment]
![image](https://github.com/user-attachments/assets/50f95014-e957-4d06-90df-2a3b832b6481)
The only possible pattern I noticed is maybe a string length issue on usernames? Because I noticed a lot of 4 letter names would go thru OK, but some longer names wouldn't. Not 100% sure on this tho, might have been coincidence on the names I happened to notice.

However, I don't think it really matters anymore. I also made the changes mentioned by @futureproof123 to not include the server name at all and I have not seen this error message since. 

I can't see any reason why people would be trying to layer someone on a different server, so these 2 minor changes to the addon seem like the right move.

**Comment by iraizo** [comment]
> I can't see any reason why people would be trying to layer someone on a different server,

because theres nothing wrong with that, why wouldn't you?

I will be looking for a fix for this, and not disregard the classic era realms.

**Comment by OriusKhan** [comment]
> > I can't see any reason why people would be trying to layer someone on a different server,
> 
> because theres nothing wrong with that, why wouldn't you?
> 
> I will be looking for a fix for this, and not disregard the classic era realms.

I think you misunderstood what I was trying to say. This addon only seems to have a Classic version, so we can assume everyone using it is on a Classic realm, correct? The Classic layers are specific to each realm. So for all General/Guild/layer chat channels where people ask to be layered that this addon will be able to see it, they all by definition will be on the same realm as you. You can ASSUME that, so you don't need to specify the realm when sending the invite.

I didn't read all the code, but if the addon happens to check whispers for the trigger words, then technically someone on a different realm could say "layer" to you on the Battle.net whisper. It would be fine for the addon to give an error at that point, in this extremely rare scenario. Because I don't believe it's even possible to invite someone to a party from a different server. (Possibly while it the same cross-server battleground?) And even if you could, it wouldn't accomplish anything. Because their realm's layers are different from yours.

I've been running the addon with the 2 very minor changes mentioned in the original post here for the past 5 days now, and it's been working perfectly fine now. Have not seen the error messages at all after that. That is the only fix needed for this. Thanks!

**Comment by iraizo** [comment]
> So for all General/Guild/layer chat channels where people ask to be layered that this addon will be able to see it, they all by definition will be on the same realm as you.

No, neither have I got a clue what definition youre talking about. Firemaw is a cluster of multiple realms, sharing the same layers, simply removing the realm name is not a functional fix.

**Comment by iraizo** [comment]
To clarify, this has to be investigated more with the thought that clustered servers exist, especialy now that their population sky rocketed.

**Comment by Starlynk1** [comment]
Posted about this on the issues in CF. Name check should check with no server before using a backup lookup with server name. Single realm servers show this message because there isn't a need to use that server name.

**Comment by iraizo** [comment]
What a headache some contributors left me.. some of the code related to handling both servers kinda got nuked but i implemented the changes either way.

Were now testing if `C_Seasons.HasActiveSeason` is true (seasonal and anniversary realms) and invite without realm name there, pushing changes & releasing, reopen if this still isnt fixed after.
